### PR TITLE
Handle 0-dimensional arrays in vectors

### LINKED ISSUE #155: Problem with vectorization and zero-length arrays
Vectorized functions don't handle the case of being passed a zero-length array (they should return a zero-length result). Instead, they assert the minimum length is always 1, and call the underlying scalar function at least once, but with garbage arguments (which can cause CSPICE to throw an error). For example:

```
    void spkez_vector(
        SpiceInt k1,
        ConstSpiceDouble *in11, SpiceInt in11_dim1,
        ConstSpiceChar *str1,
        ConstSpiceChar *str2,
        SpiceInt k2,
        SpiceDouble **out21, SpiceInt *out21_dim1, SpiceInt *out21_dim2,
        SpiceDouble **out11, SpiceInt *out11_dim1) {
        int maxdim = in11_dim1;

        int size = (maxdim == 0 ? 1 : maxdim);     <<<<==== BIG PROBLEM HERE
        in11_dim1 = (in11_dim1 == 0 ? 1 : in11_dim1);

        *out21_dim1 = maxdim; *out21_dim2 = 6;
        *out11_dim1 = maxdim;

        SpiceDouble *out21_buffer = (SpiceDouble *)PyMem_Malloc(size * 6 * sizeof(SpiceDouble));
        SpiceDouble *out11_buffer = out21_buffer ? (SpiceDouble *)PyMem_Malloc(size * sizeof(SpiceDouble)) : NULL;
        *out21 = out21_buffer;
        *out11 = out11_buffer;
        if (!out11_buffer) {
            handle_malloc_failure("spkez" "_vector");
            return;
        }

        for (int i = 0; i < size; i++) {   <<<<==== ALWAYS ITERATES AT LEAST ONCE EVEN WHEN IN11_DIM1 IS ZERO
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#pragma GCC diagnostic ignored "-Wdiscarded-qualifiers"
            spkez_c(
                k1,
                in11[i],   <<<<==== BAD MEMORY CONTENTS
                str1,
                str2,
                k2,
                out21_buffer + i * 6,
                out11_buffer + i);
#pragma GCC diagnostic pop
        }
    }
```

### PR DESCRIPTION
**Pull request by fyellin**
FIX #155 
Change the marker indicating a non-existent marker form 0 to -1.  Also made it a constant.
Changed code produced for vectorization so that if any argument has dimension 0, no work is done.

### CODE REVIEW

**Comment by fyellin** [comment]
Note to Rob.  I see above that passing Python 3.12 tests is not required for the pull request.  Can you fix that?

**Comment by rfrenchseti** [comment]
> Note to Rob. I see above that passing Python 3.12 tests is not required for the pull request. Can you fix that?

Fixed

**Comment by fyellin** [comment]
Hold off ten minutes.  Codecov is telling me that I should have added some tests for some code I added.  Will do so right now.

**Comment by rfrenchseti** [comment]
As far as I can tell this has fixed the random failures on MacOS. I'll have to try Windows after we deploy it.

**Comment by fyellin** [comment]
Pushing to Test.PyPi as we speak.  It should be finished around 3pm.

**Review by rfrenchseti — APPROVED** [review]

**Pull request merged**
